### ISSUE TITLE
Unable to Build because of issue with Spellchecker

### ISSUE THREAD

**Issue by dzlandis** [reZach/grammarify#4]
The spellchecker build appears to be failing and so I am unable to install :(

**Comment by reZach** [comment]
What environment are you trying to install the package in @dzlandis? And what version of the package are you trying to install?

**Comment by dzlandis** [comment]
> What environment are you trying to install the package in @dzlandis? And what version of the package are you trying to install?

I'm installing it with NodeJS in Visual Studio Code using NPM on Windows. Let me know if you need any additional information 👍

**Comment by reZach** [comment]
@dzlandis not sure what the fix is yet. It must have been something with a windows update and the python path as this package hasn't been recently updated.

**Comment by reZach** [comment]
@dzlandis I've updated the dependencies of this project, let me know if that fixes it for you. I am going to close out this issue - please re-open it if after getting the latest version of this package you are still seeing errors.
